Update plex_meta_manager.py
I think that the above change needs to be added otherwise the comparison on line 72 fails with the following error when I set PMM_WIDTH attribute:

Traceback (most recent call last):
File "//plex_meta_manager.py", line 72, in <module>
if screen_width < 90 or screen_width > 300:
TypeError: '<' not supported between instances of 'str' and 'int'